name: bookish
description: "A app to track your reading"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  cached_network_image: ^3.2.3
  flutter_rating_bar: ^4.0.1
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7

dependancies:
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
